# Global Settings
nameOverride: "anubis"
fullnameOverride: ""
debug: false
rollingUpdates: true
healthChecks: true
# domain: "anubis-lms.io"
domain: "anubis.osiris.services"
vpnOnly: false
imagePullPolicy: "Always"
imagePullSecret: "anubis"


###############################################################################
# Deployments with Services

# Main anubis api
api:
  replicas: 3
  workers: 2
  gunicorn_options: "--capture-output --enable-stdio-inheritance --preload --timeout 30"
  image: "registry.digitalocean.com/anubis/api"
  tag: "latest"

# Anubis web static
web:
  replicas: 2
  image: "registry.digitalocean.com/anubis/web"
  tag: "latest"

# API for submission pipeline reporting
pipeline_api:
  replicas: 2
  workers: 1

# Theia IDE proxy and poller
theia:
  enable: true

  # theia-poller deployment
  poller:
    replicas: 1

  # theia-proxy deployment
  proxy:
    replicas: 10
    image: "registry.digitalocean.com/anubis/theia-proxy"
    tag: "latest"

  prop:
    enable: true
    images:
    - name: "theia-init"
      image: "registry.digitalocean.com/anubis/theia-init:latest"
    - name: "theia-sidecar"
      image: "registry.digitalocean.com/anubis/theia-sidecar:latest"
    - name: "theia-base-38"
      image: "registry.digitalocean.com/anubis/theia-base:python-3.8"
    - name: "theia-base-39"
      image: "registry.digitalocean.com/anubis/theia-base:python-3.9"
    - name: "theia-base-310"
      image: "registry.digitalocean.com/anubis/theia-base:python-3.10"
    - name: "theia-xv6"
      image: "registry.digitalocean.com/anubis/theia-xv6"
    - name: "theia-golang"
      image: "registry.digitalocean.com/anubis/theia-golang"
    - name: "theia-software-engineering"
      image: "registry.digitalocean.com/anubis/theia-software-engineering"
    - name: "theia-jepst"
      image: "registry.digitalocean.com/anubis/theia-jepst"
    - name: "theia-devops"
      image: "registry.digitalocean.com/anubis/theia-devops"
    - name: "theia-admin"
      image: "registry.digitalocean.com/anubis/theia-admin"

# Discord Bot
discordbot:
  enable: true
  replicas: 1

marketing:
  enable: true
  domain: "anubis-lms.io"
  image: "registry.digitalocean.com/anubis/marketing-site"
  tag: "latest"
  replicas: 2

###############################################################################



###############################################################################
# Cron Jobs
reaper:
  enable: true
  suspend: false
  schedule: "*/5 * * * *"

daily_cleanup:
  enable: true
  suspend: false
  schedule: "0 4 * * *"  # 4AM

autograde_recalculate:
  enable: true
  suspend: false
  schedule: "*/30 * * * *"

visuals:
  enable: true
  suspend: false
  schedule: "*/5 * * * *"

backup:
  enable: true
  suspend: false
  schedule: "0 0 * * *" # Midnight
  secretName: anubis-backup-creds
###############################################################################


###############################################################################
# RPC Pools
rpc:
  replicas: 3
  queues: ["default", "theia", "regrade"]
###############################################################################


###############################################################################
# Horizontal Pod Autoscaling
hpa:
  enable: true
  rpc:
  - name: rpc-default
  - name: rpc-theia
  - name: rpc-regrade
###############################################################################

